// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using retronatus_backend.Context;

#nullable disable

namespace retronatus_backend.Migrations
{
    [DbContext(typeof(RetronatusContext))]
    [Migration("20230618233525_populaUsuario")]
    partial class populaUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("retronatus_backend.Model.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcategoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("IdCategoria");

                    b.ToTable("categoria");
                });

            modelBuilder.Entity("retronatus_backend.Model.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcomentario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("IdPublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("idpublicacao");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<int?>("PublicacaoIdPublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("publicacaoidpublicacao");

                    b.HasKey("IdComentario");

                    b.HasIndex("PublicacaoIdPublicacao");

                    b.ToTable("comentario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idlocal");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("IdLocal");

                    b.ToTable("local");
                });

            modelBuilder.Entity("retronatus_backend.Model.Media", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmedia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedia"));

                    b.Property<int>("IdPublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("idpublicacao");

                    b.Property<int?>("PublicacaoIdPublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("publicacaoidpublicacao");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("IdMedia");

                    b.HasIndex("PublicacaoIdPublicacao");

                    b.ToTable("media");
                });

            modelBuilder.Entity("retronatus_backend.Model.Publicacao", b =>
                {
                    b.Property<int>("IdPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpublicacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPublicacao"));

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("categoriaidcategoria");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("idcategoria");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer")
                        .HasColumnName("idlocal");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<int?>("LocalIdLocal")
                        .HasColumnType("integer")
                        .HasColumnName("localidlocal");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioidusuario");

                    b.HasKey("IdPublicacao");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("LocalIdLocal");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("publicacao");
                });

            modelBuilder.Entity("retronatus_backend.Model.Resposta", b =>
                {
                    b.Property<int>("IdResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idresposta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResposta"));

                    b.Property<int?>("ComentarioIdComentario")
                        .HasColumnType("integer")
                        .HasColumnName("comentarioidcomentario");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("IdComentario")
                        .HasColumnType("integer")
                        .HasColumnName("idcomentario");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.HasKey("IdResposta");

                    b.HasIndex("ComentarioIdComentario");

                    b.ToTable("resposta");
                });

            modelBuilder.Entity("retronatus_backend.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("Is_Super_Admin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_super_admin");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Comentario", b =>
                {
                    b.HasOne("retronatus_backend.Model.Publicacao", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacaoIdPublicacao");
                });

            modelBuilder.Entity("retronatus_backend.Model.Media", b =>
                {
                    b.HasOne("retronatus_backend.Model.Publicacao", null)
                        .WithMany("Medias")
                        .HasForeignKey("PublicacaoIdPublicacao");
                });

            modelBuilder.Entity("retronatus_backend.Model.Publicacao", b =>
                {
                    b.HasOne("retronatus_backend.Model.Categoria", null)
                        .WithMany("Publicacoes")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("retronatus_backend.Model.Local", null)
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalIdLocal");

                    b.HasOne("retronatus_backend.Model.Usuario", null)
                        .WithMany("Publicacoes")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Resposta", b =>
                {
                    b.HasOne("retronatus_backend.Model.Comentario", null)
                        .WithMany("Respostas")
                        .HasForeignKey("ComentarioIdComentario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Categoria", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("retronatus_backend.Model.Comentario", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("retronatus_backend.Model.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("retronatus_backend.Model.Publicacao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Medias");
                });

            modelBuilder.Entity("retronatus_backend.Model.Usuario", b =>
                {
                    b.Navigation("Publicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
