// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using retronatus_backend.Context;

#nullable disable

namespace retronatus_backend.Migrations
{
    [DbContext(typeof(RetronatusContext))]
    [Migration("20230612173235_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("retronatus_backend.Model.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("retronatus_backend.Model.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComentario"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPublicacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicacaoIdPublicacao")
                        .HasColumnType("integer");

                    b.HasKey("IdComentario");

                    b.HasIndex("PublicacaoIdPublicacao");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Local", b =>
                {
                    b.Property<int>("IdLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLocal"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("IdLocal");

                    b.ToTable("Local");
                });

            modelBuilder.Entity("retronatus_backend.Model.Media", b =>
                {
                    b.Property<int>("IdMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedia"));

                    b.Property<int>("IdPublicacao")
                        .HasColumnType("integer");

                    b.Property<int?>("PublicacaoIdPublicacao")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("IdMedia");

                    b.HasIndex("PublicacaoIdPublicacao");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("retronatus_backend.Model.Publicacao", b =>
                {
                    b.Property<int>("IdPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPublicacao"));

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdLocal")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalIdLocal")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdPublicacao");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("LocalIdLocal");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Publicacao");
                });

            modelBuilder.Entity("retronatus_backend.Model.Resposta", b =>
                {
                    b.Property<int>("IdResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdResposta"));

                    b.Property<int?>("ComentarioIdComentario")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdComentario")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdResposta");

                    b.HasIndex("ComentarioIdComentario");

                    b.ToTable("Resposta");
                });

            modelBuilder.Entity("retronatus_backend.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("Is_Super_Admin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Comentario", b =>
                {
                    b.HasOne("retronatus_backend.Model.Publicacao", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacaoIdPublicacao");
                });

            modelBuilder.Entity("retronatus_backend.Model.Media", b =>
                {
                    b.HasOne("retronatus_backend.Model.Publicacao", null)
                        .WithMany("Medias")
                        .HasForeignKey("PublicacaoIdPublicacao");
                });

            modelBuilder.Entity("retronatus_backend.Model.Publicacao", b =>
                {
                    b.HasOne("retronatus_backend.Model.Categoria", null)
                        .WithMany("Publicacoes")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("retronatus_backend.Model.Local", null)
                        .WithMany("Publicacoes")
                        .HasForeignKey("LocalIdLocal");

                    b.HasOne("retronatus_backend.Model.Usuario", null)
                        .WithMany("Publicacoes")
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Resposta", b =>
                {
                    b.HasOne("retronatus_backend.Model.Comentario", null)
                        .WithMany("Respostas")
                        .HasForeignKey("ComentarioIdComentario");
                });

            modelBuilder.Entity("retronatus_backend.Model.Categoria", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("retronatus_backend.Model.Comentario", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("retronatus_backend.Model.Local", b =>
                {
                    b.Navigation("Publicacoes");
                });

            modelBuilder.Entity("retronatus_backend.Model.Publicacao", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Medias");
                });

            modelBuilder.Entity("retronatus_backend.Model.Usuario", b =>
                {
                    b.Navigation("Publicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
